### ISSUE TITLE
Fix MODsulator  spreadsheet upload

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#101]
With Monday's release of Argo, spreadsheet upload stopped working. It takes an upload and silently fails, leaving no evidence it was even submitted. This is a production outage

**Comment by ndushay** [comment]
timebox 2 hours max investigation;  return to team when investigation is complete or when 2 hours have been spent on it - whichever comes first.

**Comment by ndushay** [comment]
one possible culprit:  reindexing everything for the argo rights facet - all the workers are occupied (?)

**Comment by ndushay** [comment]
our theory SEEMS to have been correct, as a spreadsheet in prod surfaced - like maybe it was getting through the queus finally.
