### ISSUE TITLE
Test (supported) browsers across (OS) platforms - possibly w tool

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#108]
Determine if Stanford has a tool for cross-platform browser testing too for verifying media playback across browsers/platforms.

Potential issue: before deployed to production, test sites are behind VPN.

**Comment by ndushay** [comment]
cross-browser testing service won't work due to VPN needed for testing.

**Comment by ndushay** [comment]
aren't aware of tool we can use.  Closing in favor of #92
