### ISSUE TITLE
set up honeybadger error notification service for wowza

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#109]
We will need API key from @eefahy (?)  and will need to use something like  https://github.com/honeybadger-io/honeybadger-java  in the dlss-wowza plugin.    We may _also_ want to do something for the wowza server itself, beyond our plugin code (e.g. for sul-streaming wowza application).

For a ruby example, see https://github.com/sul-dlss/exhibits/pull/291

**Comment by eefahy** [comment]
In order to mint a new project and API key in HoneyBadger, I first need to make a team in invite everyone to join it. Admin users of the team can then make their own projects in honeybadger which will mint an API key to use.

**Comment by ndushay** [comment]
So does this mean we want the "whiskey" team (formerly known as margo, formerly known as media) to be created with Jessie, myself, Tommy and John all as admins?  Or just Jessie and myself?  Or ...?

**Comment by eefahy** [comment]
Yep, I think all devs in the `whiskey` team should be added. I will make a team and add you, Jessie, Tommy, and John
