### ISSUE TITLE
Questions: how does authorization tie into Wowza server?

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#11]
When a user requests an image from the image stacks, a check against rights metadata is performed to determine their access rights.  If access is granted, the image is then retrieved and passed along to the user's browser.

Something similar needs to occur with media from the Wowza server.  Instead of having the media file stream directly from Wowza to the embedded video player, there needs to be some intermediate check of rights for the object.  Only after access rights have been confirmed can the media playback occur.  This work is to define architecturally how this will work and come up with a plan. 

Lynn has done architecture diagrams here: https://consul.stanford.edu/display/GAL/Media+Stacks

**Comment by hannahfrost** [comment]
Related user stories:
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-32
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-33
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-28 - This one suggests that auth may be required for the streamed media but not for the associated non-media files. How does that work?
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-9 - Where the user is a digitization tech

And the location-specific authorization stories:
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-36 - reading room access
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-35 - reading room workstation
https://jirasul.stanford.edu/jira/browse/MEDIAINFRA-53 - reading room access to Stanford-only content by non-SUNET holder

**Comment by peetucket** [comment]
- Can we construct a token for Wowza so it can tell if it stream or not?
  alt:  Avalon might have some middleware they use to pass a token to and get a list of accessible files in return (?)
- How does Stanford’s auth work?   JK can speak to this
- How does existing auth work for image stacks auth work?   LM / ….   can speak to this
- is there a diff between media stacks authzn and image stacks authzn?  
      dor rights modules?

**Comment by ndushay** [comment]
We had a discussion and roughed out a design to prototype.  See https://github.com/sul-dlss/media/wiki/Authentication-discussion-April-12,-2016---Images
