### ISSUE TITLE
UX: ensure good UX when media rejected for flash player

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#110]
When stacks token is not authorized by dlss-wowza plugin, we need to ensure that the UX is ok - may involve changes to dlss-wowza plugin, sul-embed js, etc.

**Comment by ndushay** [comment]
See also #14

**Comment by ndushay** [comment]
sul-embed should be checking for permissions before user sees flash player part ... but perhaps someone will get to this ...

**Comment by hannahfrost** [comment]
And then the default player error message shows, and we wonder if that is acceptable to users.  We could contrive this exception and get input from @jvine or evaluate it in the event it happens in production.

**Comment by ndushay** [comment]
I'm closing this.  If something problematic is discovered that got by our testing, we'll open a new ticket then.
