### ISSUE TITLE
Verify File Name Encoding Consistency Through Stack

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/media#115]
We are seeing some tokens be rejected for files w/ spaces in their titles.  We need to look at the URLs that Embed is sending to wowza and the URLs that wowza is sending to stacks (for token verification).

**Comment by jkeck** [comment]
See sul-dlss/sul-embed#578 as well.

**Comment by ndushay** [comment]
Note this:  https://github.com/sul-dlss/digital_stacks_rails/commit/287304de5adb0f5190fce79f2b1c4d97d9b711e7

I'm wondering if periods and other special chars in the stream name need to be properly encoded in the verify_token request params?

**Comment by jkeck** [comment]
Immediate issue has been addressed.  More validation will happen in sul-dlss/sul-embed#578
