### ISSUE TITLE
Anaylze storage options for media content accessible to wowza server

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/media#12]
can end user download and streaming be off the same copy?

will it scale?

**Comment by LynnMcRae** [comment]
implicit in this question is whether Wowsa can work off whatever file path (i.e. druid tree) and filename we give it as file location.

**Comment by peetucket** [comment]
Analyze how Wowza performs with content mounted via different mechanisms (nfs mount vs AWS vs local) and report on performance.

**Comment by peetucket** [comment]
split into #18, #19, #20, #21
