### ISSUE TITLE
Update SMPL's pre-assembly script to support image thumbs in media objects

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/media#120]
SMPL uses a script to generate a manifest about content to be accessioned. In order to take advantage of new image thumb functionality for media objects, the script should be updated.

Link to documentation about the script is here: https://consul.stanford.edu/pages/viewpage.action?pageId=136365158#AutomatedAccessioningandObjectRemediation(pre-assemblyandassembly)-SMPLContent

**Comment by hannahfrost** [comment]
@peetucket I mentioned that I would dropping this ticket in DEVQUEUE, but thought it wiser to put it in the media github backlog.

**Comment by blalbrit** [comment]
I _think_ the work to be done is in the pre-assembly code-base: https://github.com/sul-dlss/pre-assembly/blob/ea3c4e5580fbdc773eff2a272a4aa85d5924e391/lib/pre_assembly/smpl_precontent_metadata.rb

If possible, it would be awesome if @peetucket could pair with someone on this so we get more eyes on that code base?

**Comment by peetucket** [comment]
yes, this would happen in the pre-assembly codebase, i'll move it there, connect the pre-assembly project to the media waffle and perhaps this can be addressed by the media team if there  is time this week.  i'd be happy to pair with another developer to spread the knowledge

**Comment by peetucket** [comment]
moved to https://github.com/sul-dlss/pre-assembly/issues/26
