### ISSUE TITLE
Add location and no-download options to Argo rights-setting tools

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#131]
Proxy ticket for https://github.com/sul-dlss/argo/issues/796

**Comment by hannahfrost** [comment]
@jmartin-sul Yesterday I spoke with @jvine about this outstanding ticket and she understands that we need this to help close out the media work cycle. Please feel free to work on this as we discussed. If it is taking longer than the estimated 2 days, let us know. Thank you!
