### ISSUE TITLE
Support new location (whitelisted IP address) for location-based content access

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/media#138]
We need to enable location-based access to another workstation; this one is in the Archive of Recorded Sound. Please update the configuration with the following information:

IP address: 171.67.134.179
identifier: ars

**Comment by ndushay** [comment]
deployed to -stage and -uat.

**Comment by ndushay** [comment]
deployed stacks to -prod.   Note that sul-dlss/argo#862   is needed before this is truly finished.

**Comment by LynnMcRae** [comment]
adding new locations over time is an ongoing concern with separate tickets. Closing this initial implementation ticket since the facility is now in production.
