### ISSUE TITLE
UX: What to display when streaming is forbidden?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#14]
e.g.  thumbnail?   mechanism for users to request access if they don't already have it?

presumably sul-embed already has a mechanism to tell users to log in??

@jkeck believes there may be some design work sketched out somewhere?

**Comment by LynnMcRae** [comment]
I think this applies to the gentler use case of showing something (thumb, keyframe, placeholder) for, say, Stanford-only access before the user has authenticated, assuming the video would otherwise be "queued up" and ready to play.  I can't claim to know if I am painting this picture correctly.

**Comment by ndushay** [comment]
sul-embed should be handling this gracefully, tho there may be exception cases

**Comment by ndushay** [comment]
I'm closing this - we'll open a new ticket if something needs tweaking
