### ISSUE TITLE
Thumbnails for media files tend to look pixelated

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/media#140]
Not sure why. The jp2s look great on their own after Michael A. creates them, but once they're in embed, there's a noticeable drop in quality. qy650sk8658 is a good example (I can't attach the original jp2 to this ticket).

![screen shot 2016-11-17 at 10 27 24 am](https://cloud.githubusercontent.com/assets/1029087/20402472/b5b5c484-acb1-11e6-9935-2649f463382a.png)

**Comment by hannahfrost** [comment]
Are the jp2s further processed during accessioning? Would it be better to submit TIFFs and have the thumbnail jp2s producing during assembly? Or is the player doing something funky? Does the player prefer a different image format?

**Comment by hannahfrost** [comment]
We picked the safest public version of the images to display.

A IIIF compatible media player could be built to address this.
