### ISSUE TITLE
Upgrade Wowza

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/media#142]
Wowza Streaming Engine was recently updated to version 4.6. There is also a Wowza Player that is now available.

We should consider updating the Wowza Streaming Engine at the first good opportunity, and maybe also look into what features the player provides.

**Comment by hannahfrost** [comment]
Now at 4.7.3

**Comment by cbeer** [comment]
Looks like we're on 4.7.6.. getting to 4.8 will have to wait for server migrations to come around to this stack.
