### ISSUE TITLE
Latest version of Wowza has MP3 problems

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/media#144]
We've updated from Wowza version 4.5.0 to 4.7.1 on the stage server. Videos seem to work fine, but there are problems with streaming MP3 files:

- Safari plays fine
- Chrome plays fine IF you allow [*.]stanford.edu to play Flash
- Opera doesn't work ("No compatible source was found for this media")
- Firefox appears to load the audio and play it OK (looking at the player) but there is no sound.

This problem appears only in -stage, not in -prod (note that -prod is still running the older Wowza version). A couple of example URLs:

https://sul-purl-test.stanford.edu/bb051hp9404

https://purl.stanford.edu/bb051hp9404

**Comment by tingulfsen** [comment]
I mentioned this to Jessie and we agreed I should try to dig around/ask in the Wowza forums over the next week or so.

**Comment by hannahfrost** [comment]
We are systematically replacing accessioned MP3 files with M4A files to get around this matter.

**Comment by hannahfrost** [comment]
consider trying the latest release, 4.7.3

**Comment by tingulfsen** [comment]
Tony has installed Wowza 4.7.5 in the stage environment. My brief and informal testing shows that the Firefox problem mentioned above seems to be fixed.

**Comment by oceanofsound** [comment]
That's great news!

**Comment by tingulfsen** [comment]
Wowza has been upgraded to 4.7.6.
