### ISSUE TITLE
Error on jt334pp3958 when viewing on iOS mobile browsers 

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/media#148]
Discovered by Michael A. Viewing jt334pp3958 on an iOS browser (we checked Chrome and Safari) triggered the following error: 'The media playback was aborted due to a corruptions problem or because the media used features your browser did not support.'

Spot checking other druids from this accessioned batch do not reveal the same error (see: https://jirasul.stanford.edu/jira/browse/LEGACY-3511). Perhaps an anomaly, but if we discover others, we'll add them to this ticket.

**Comment by hannahfrost** [comment]
@oceanofsound Did we try replacing this mp4 file with a newly created one?

**Comment by oceanofsound** [comment]
We haven't, although I can confirm that it still doesn't work in either of those two browsers.

**Comment by dinahhandel** [comment]
@oceanofsound still an issue? Has the file been replaced?

**Comment by oceanofsound** [comment]
Still an issue, file was never replaced.

**Comment by oceanofsound** [comment]
I'll try replacing the file now and see what happens.

**Comment by oceanofsound** [comment]
Works now!
