### ISSUE TITLE
Media will not stream correctly on Windows 10 browsers

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/media#150]
When we presented Henry Lowood with four PURLs to check out, he reported the following:

In Edge browser: Players shows a static frame with message, “no compatible source was found for this media.” Checked all four interviews.
In Chrome browser: Player seems to start and I can see and advance progress bar, but no video. After moving the progress bar a couple of times, the transcript (!) shows in the video window instead of image frames.  This was the Carter interview.  With Wells, just the image, otherwise the same – no video, progress bar shows, etc.

https://purl.stanford.edu/bv547jn0626
https://purl.stanford.edu/nc497jv0418
https://purl.stanford.edu/sr362zy3253
https://purl.stanford.edu/xh983pf4267

There's a computer in SPEC with Windows 10 that I could use to replicate the issue on Edge (on accessioned audio AND video content), however it did not have Chrome installed. Long story short: more testing on Windows 10 is needed.

**Comment by peetucket** [comment]
I did not have this experience on my personal Windows 10 tablet running at home.  Video worked as expected with progress bars and audio on Chrome and Opera for me.  In Edge, the audio worked fine, but there was no progress and the video was replaced with a sort of slideshow (like 1 frame every few seconds).  I am running latest Windows 10 and latest version of all browsers.

**Comment by oceanofsound** [comment]
Good to know. I'll see if Henry's personal computer (assuming he's on Windows 10) is similarly successful at viewing streaming media.

**Comment by oceanofsound** [comment]
Follow up from Henry: "I checked Morgan and Carter at home on a W10 PC, desktop with Ethernet connection. Edge was the same as on campus – “no compatible media” error showing in player. BUT: Chrome worked fine: video and audio, synced; progress bar; static images popping up. Beats me why this would be."

**Comment by hannahfrost** [comment]
cannot reproduce.
