### ISSUE TITLE
Stanford only login link doesn't disappear after authenticating

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#151]
Visit a video that requires stanford auth to view in a browser that is not already authenticated, e.g. : https://purl.stanford.edu/tx321yn8364

Click the red link to go through auth and start playing.  The video is able to play, but the red "login to play" link does not go away (it correctly does not show on page reload, or if already authed before getting to the page).

**Comment by hannahfrost** [comment]
This behavior is apparently only occurring on objects that do not allow download.

**Comment by oceanofsound** [comment]
This bug still exists, although I believe the link will disappear if you come to a resource already authenticated. Still, it comes and goes, and with our resources getting more eyeballs, I could foresee questions about it.
