### ISSUE TITLE
Control bar disappears on audio object with thumb in iOS

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/media#156]
Normally we do not add thumbs to audio objects, but recently we had a request to do so: https://argo.stanford.edu/view/druid:vc092km4494

On iOS 14.4 in both Safari and Chrome the control bar is not visible after playback is started. Shuttling through the resource appears to be impossible.

**Comment by hannahfrost** [comment]
User reports a similar issue with this video object: https://purl.stanford.edu/tw262dt8340
"I'm getting a strange view of the Taking the Mic video on some, but not all computers.  It looks all crunched up in a very narrow bar (with no ability to manipulate to make larger or access bottom bar controls) on my apple desktop, which is  an IMAC 2019 running macOS Mojave 10.14.6 and Safari 14.0.1 But it's fine on my apple laptop (which is running a bit behind on updates and is on safari 13.1.2 and MacOS High Sierra). Josh Schneider had the same problem on Safari."

<img width="1181" alt="media player issue" src="https://user-images.githubusercontent.com/1801076/108901071-3e5e9c80-75cf-11eb-83e0-886fc4d7f0f9.png">

**Comment by hannahfrost** [comment]
Further investigation shows that the issue does not appear in the viewer in SW, only PURL.
<img width="2186" alt="Screen Shot 2021-02-23 at 12 23 29 PM" src="https://user-images.githubusercontent.com/1801076/108929333-af667a00-75f8-11eb-9e9b-2bd0c780c7ef.png">

**Comment by oceanofsound** [comment]
This bug does not appear to be an issue anymore.
