### ISSUE TITLE
Evaluate performance of nfs as storage for media content

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#19]

**Comment by ndushay** [comment]
There are nfs mounts for  prod and stage wowza servers  in   /data  directory

**Comment by peetucket** [comment]
may be able to do concurrent with #21

**Comment by tingulfsen** [comment]
I'm closing this ticket with reference to https://github.com/sul-dlss/wowza_load_tester

John, Naomi and I did some basic load testing to see how long it takes for a video to start playing when loaded via an NFS-mounted directory, and the load times we saw seemed completely reasonable.
