### ISSUE TITLE
Evaluate performance and URL rewriting for storing content in a druid tree folder format

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#21]

**Comment by peetucket** [comment]
related to #19

**Comment by ndushay** [comment]
Tommy, you did this, yes?  If so, feel free to close the ticket.

**Comment by tingulfsen** [comment]
URL rewriting has been evaluated and found to work well. However, we have decided that the Digital Stacks will simply redirect to the fully expanded DRUID path on the Wowza server, so no URL rewriting is required.

We did a quick evaluation of player speed when streaming from an NFS mounted directory (see sul-dlss/wowza_load_tester), and found the performance to be adequate.
