### ISSUE TITLE
test migration from sul-streaming to wowza: handful of files

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#22]
Get a few files from the sul-streaming server onto the wowza server, just to ensure we can get them and that the formats will work, etc.

from @oceanofsound: 

some files from the old streaming server that are world accessible, 
- University Archives content would be the way to go.  
- They’re on sul-streaming, username=media.
- path is /usr/local/wow/content
- the UA stuff is all in 
  - ‘scXXXX’ folders, from SC0059 to SC1135
    - the only content that’s not world visible in that set are the MP3s in sc1118
  - ‘vXXXX’ folders

**Comment by ndushay** [comment]
Julian has hooked me up with access to media account on sul-streaming, and will get the other developers too.  sul-streaming box predates puppet!

**Comment by jmartin-sul** [comment]
i tested this with a handful of the sample mp3 and flv files which were recommended above (copied from sul-streaming to sul-wowza-stage, and served from sul-wowza-stage's NFS mount).  i found that the mp3 files played fine in both the adobe RTMP and the adobe HDS player, as long as mp3 was specified as the desired format (e.g., `mp3:sc0359/vq083my4984_b_sl.mp3`).  the flv files played fine in the adobe RTMP player as long as flv was specified as the desired format (e.g. `flv:v0058/pw607mn4286_web.flv`), but didn't play in the adobe HDS player.  none played in the DASH player (though wowza gives a clear "Warning: You may experience inconsistent playback using this third-party beta DASH test player.").  none played when mp4 was specified as the playback format.

does that cover the testing we want for this issue, or is there more to be done?  are any of the above results unexpected?  mp3 files used for testing ranged from 20 MB to 70 MB, and flv files used for testing were 402 MB and 530 MB.

**Comment by hannahfrost** [comment]
I think this is totally expected behavior, @jmartin-sul, and I think you have covered it.

**Comment by jmartin-sul** [comment]
great, closed, thanks for the confirmation, @hannahfrost
