### ISSUE TITLE
Create wowza module/plugin to confirm validity of tokens from stacks

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#30]
Wowza plugin that evaluates the validity of a token provided in the request

it should confirm the token is valid

**Comment by ndushay** [comment]
This would be in java;  we would want a git repo, tests, travis, a release and deploy strategy

**Comment by ndushay** [comment]
This ticket has been split into:
- #41
- sul-dlss/dlss-wowza#1
- sul-dlss/dlss-wowza#2
- sul-dlss/dlss-wowza#4
- sul-dlss/dlss-wowza#5

@peetucket  do you want to close this one as a dup?   I have put estimates on the other tickets ...

**Comment by peetucket** [comment]
closed due to being split into issues above
