### ISSUE TITLE
Adjust default token and connection timeouts

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#31]
ensure player allows access after a pause and seek operation and then expiration of a token (short time to live) does not cause issues

**Comment by peetucket** [comment]
What the correct time out period?
Should the token work until first viewed or does the time out period begin upon creation?
Can we tie the token to the session?

**Comment by peetucket** [comment]
to have a full end to end test, we need the whole stack operational

**Comment by ndushay** [comment]
blocked by sul-dlss/dlss-wowza#2

**Comment by ndushay** [comment]
Note that token expiry should have a relationship to the connect and read timeouts for connections from wowza to stacks

**Comment by ndushay** [comment]
Set the DEFAULT token time to a reasonable number, and the connection and read timeouts, too.

**Comment by ndushay** [comment]
Without load testing, we're thinking these defaults:

45 seconds chosen for token expiry
20 seconds for wowza connection timeout
20 seconds for wowza read timeout
