### ISSUE TITLE
Create media we can use for testing in stacks-test

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#34]
Accession 4 objects available in stacks-test/purl-test for testing media player and authentication.  

2 audio (mp3), 1 each world and stanford only
2 video (mp4), 1 each world and stanford only

example mp4 = https://purl.stanford.edu/bd786fy6312 and https://purl.stanford.edu/bb582xs1304

example mp3 = https://purl.stanford.edu/bb051hp9404 and https://purl.stanford.edu/cc340qm0511

example mov if needed = https://purl.stanford.edu/bb879jv3823

**Comment by ndushay** [comment]
I think this may duplicate #5 ??

**Comment by peetucket** [comment]
Yes, @ndushay this sounded like a dupe of #5 to me too, though I thought #5 involved creating some hand-crafted, organic, grass-fed contentMetadata?  Or is that not necessary anymore?

**Comment by ndushay** [comment]
dunno.  We can always ticket anew for that?  or you can reopen and revise #5

**Comment by blalbrit** [comment]
Okay @ndushay and @peetucket - should I work this or not?

B.

**Comment by ndushay** [comment]
@blalbrit yes, please, by all means.  We are talking about OTHER tendrils.

**Comment by blalbrit** [comment]
https://argo-stage.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Media+Fixture+Objects&page=1

**Comment by blalbrit** [comment]
@peetucket - go ahead and close if this satisfies.

**Comment by ndushay** [comment]
@blalbrit   would you please also do the same for  https://purl.stanford.edu/bb879jv3823  ?

**Comment by blalbrit** [comment]
done - added to Media Fixture Objects accessible from link above.
