### ISSUE TITLE
checksum script:  update  (to ruby v2.x) and fix

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/media#35]
https://jirasul.stanford.edu/jira/browse/DEVQUEUE-33

which starts:

https://github.com/sul-dlss/checksum-tools

Old software originally written by Michael Klein, but still in daily use by SMPL staff. The 1.8.7 requirement is a little annoying, however we've dealt with it up until now. Not being able to remotely generate and verify checksums on the sul-smpl volumes is a little more of a deal breaker. Up until now we've used Fuse for OS X to mount the volumes and use the tool "locally." A typical remote call without using Fuse might look like this:

checksum-tools -a generate -e .md5 smpl@sul-smpl.stanford.edu:/pool0/smpl8/test/

which now returns:

/Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools/remote.rb:124:in `remote_properties': Checksum Tools not configured for smpl@sul-smpl.stanford.edu. Please use the --openssl parameter to specify the location of the remote openssl binary. (Checksum::Tools::ConfigurationError)
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools/remote.rb:28:in`openssl'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools/remote.rb:78:in `digest_file'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools/remote.rb:77:in`each'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools/remote.rb:77:in `digest_file'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools.rb:62:in`create_digest_file'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools.rb:52:in `create_digest_files'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools.rb:163:in`process_files'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools.rb:162:in `each'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools.rb:162:in`process_files'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/lib/checksum-tools.rb:50:in `create_digest_files'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/bin/checksum-tools:42:in`generate'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/gems/checksum-tools-1.0.7/bin/checksum-tools:169
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/bin/checksum-tools:19:in `load'
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/bin/checksum-tools:19
from /Users/gwillard/.rvm/gems/ruby-1.8.7-p370/bin/ruby_noexec_wrapper:14

**Comment by ndushay** [comment]
@mbklein!!!!!!!!!!!!

**Comment by jkeck** [comment]
I have released a [beta version of checksum-tools](https://rubygems.org/gems/checksum-tools/versions/1.2.0.beta1) with support for Ruby2 and remote authentication via password for testing by SMLP.

Testing will continue Friday, and will table this until then.  If all goes well, we'll simply drop the `beta` version and release a legitimate 1.2.0.

**Comment by jkeck** [comment]
[checksum-tools v1.2.0](https://rubygems.org/gems/checksum-tools/versions/1.2.0) has been released.
