### ISSUE TITLE
Add support for AUDIO streaming on non-safari browsers

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/media#36]
We'll be using DASH for video, but we'll need to find a solution for audio.

**Comment by ndushay** [comment]
https://github.com/sul-dlss/media/wiki/Current-Media-Viewer-Progress

**Comment by jkeck** [comment]
Video.js may have an HLS plugin that will work for audio on non-safari browsers

**Comment by tingulfsen** [comment]
Per videojs/videojs-contrib-hls#803, MP3 files are not supported by the VideoJS HLS plugin. However, AAC encoded audio is supported (I tried successfully with an AAC-encoded audio file inside an MP4 container).
