### ISSUE TITLE
Determine how to get accessioned objects to wowza

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#4]
- can wowza use files in digital stacks?
- conventionally shelve media files in druid tree
- is contentMetadata file_id sufficient info (from purl page) or does more need to be on purl-page

Note:  we already have some shelving robot code to shelve to other places (e.g. for WARC);  we may need to do something similar for media.

Would prefer not to duplicate large objects -- maybe digital stacks can point to wowza copy or vice versa.

**Comment by LynnMcRae** [comment]
There has been some discussion about whether media should be partitioned in the stacks for other, operational reasons ... based primarily on their very large size and for independent space management.

**Comment by peetucket** [comment]
Reading straight from the stacks - this ticket is no longer needed.
