### ISSUE TITLE
Argo - Add check for null in the controller for bulk upload

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#45]
This is a proxy ticket for https://github.com/sul-dlss/argo/issues/734

A check for missing log files might be a simple short term fix if it allows users access to the upload screen.  The cause of the missing log files might also get fixed but can be deferred to a future ticket if necessary.

**Comment by ndushay** [comment]
PR for this https://github.com/sul-dlss/argo/pull/742

**Comment by LynnMcRae** [comment]
Related ticket close, change is good to go.
