### ISSUE TITLE
Create an object in dor-test that can be published to purl-test to representive files on wowza

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#5]
Question:  why do we need this?  sul-embed will interact with media in a read-only way;  is this so we can experiment with the contentMetadata information from the appropriate robot????

dimensions:
- formats
- density of data
- definition level of data
- corresponding metadata

Current assumption:  we can put it on purl test and that will be adequate for testing.

Wondering about performance of purl test / stacks stage etc.

**Comment by ndushay** [comment]
From #2:

audio: https://purl.stanford.edu/bb051hp9404 
video: https://purl.stanford.edu/bb582xs1304

Each of these are exemplary, because:
- the audio object includes an MP3 that represents our typical file specs. It should be streamable by Wowza as is.
- the audio object includes a PDF transcript, which is not uncommon for oral history audio objects and we'll need to eventually find a way to handle in sul-embed/purl
- the video object includes an MP4 that represents our typical file specs. It should be streamable by Wowza as is.
- the video object includes images of the original video tape. Almost all digitized media coming from SMPL will have one or more jp2s that we'll need to support somehow someday.

**Comment by ndushay** [comment]
Is this a @hannahfrost  thing?   I'm not sure I know how to do this - does anyone else?

**Comment by jkeck** [comment]
I believe @LynnMcRae and @hannahfrost were going to work on this.

**Comment by ndushay** [comment]
@LynnMcRae wants to be sure that @hannahfrost is comfortable with us closing this ticket now;   we think we can use prod purl videos for testing, and when we are working on accessioning issues they will be ticketed separately.

**Comment by ndushay** [comment]
Closing in favor of #34
