### ISSUE TITLE
Determine strategy for audio and video thumbs

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#51]
Thumbnails provide a visual reference for objects and greatly enhance a users experience when scanning items online, especially if they aid in recognizing a particular item.  Thumbs are used in the "filmstrip" representation of items in a collection and accompany each item in a search result in Searchworks.

Unless determined otherwise, Media objects should get the same basic thumbnail treatment as any object, to wit, it will create a thumb from
   -- any resource of type=thumb or type=image marked with the attribute thumb=yes
   -- the first resource of type=image or type=page
For more precise rules, see https://consul.stanford.edu/display/chimera/The+Rules+of+Thumb

Some object will have accompanying images that make a natural thumb -- picture of media, poster, etc.  This ticket addresses two questions when this is not the case. 
1. under what circumstances will a project endeavor to provide distinct thumbs and what support might be needed. A keyframe from a video as thumb is a subset of this addressed by a separate ticket.
2. what behavior do we want when there is no thumb?  A placeholder for the collection filmstrip (new behavior in embed, declared in manifests)? simply omit thumbs in all other contexts? This is needed no matter how common or rare a missing thumb might be.

**Comment by hannahfrost** [comment]
@LynnMcRae Do we still need this ticket?

**Comment by LynnMcRae** [comment]
This is my current understanding of what we've decided:

Object thumbs will not be represented in the audio or video display in embed; they will limit themselves to their current role of decorating search results and filmstrips etc. They are however offered for download among the other files in the embed download list.

We do have plans for using image files placed in a resource accompanying a media file to be the means to add file-specific keyframes (video) or "art" to an otherwise blank audio embed frame.  This work is not currently in scope I think, but the current Embed blindly finds these image files and treats them as peers to image files found in "resource type=image" resources. It shows them as if they were separate resources in a mixed object-type object and offers them for download as peers files as well. The plan is for embed to completely ignore these files until we confirm the model for explicit keyframes and related use cases.

So this ticket is not needed if all agree ("strategy...determined!"); I'm not seeing a ticket for the latter bit of work however. I'm happy to make one in sul-embed if needed.
