### ISSUE TITLE
Design location based authorization for media

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#55]
This is a story to capture the strategy for support and to identify the various tickets across other projects that are involved. Syntax for recording location restrictions have been specified in #28. This story covers the implementation of those rights.

We are planning a first implementation that is based on mapping a named location in rightsMetadata to an associated set of whitelisted IP-addresses. Further investigation will determine if it will be exact addresses or if we can work in ranges, or host names/patterns, or a combination to assure we are actually talking to only blessed machines over time. This strategy was chosen because it is a passive interpretation of the user's environment and will require no intervention into the system image of closed-kiosks and related staff machines.

Here are the pieces of the implementation identified so far, with individual tickets to be made in appropriate projects as needed. 
1. Determine actual locations and names and gather information on machine identities (Lynn)
2. Add consideration for location restrictions to the UI requirements (Lynn to write up for Jennifer)
3. Update dor-rights-auth to convey <location> information in its interpretation of rights
4. Update Digital stacks to hold the location definitions, that is, the mapping of location to addresses
5. Update Digital stacks to apply location restrictions to the authorization equation

We noted the need to review the rules of ANDing criteria within a rightsMetadata access block vs ORing across blocks since we want flexibility in how Stanford-only and location are combined (a choice between either or both)

**Comment by ndushay** [comment]
Is this an implementation ticket or a design the implementation ticket?   Also, is it now to be closed in favor of other tickets for steps of the work?

**Comment by LynnMcRae** [comment]
Items 1 and 2 have been done (though refinement of location information will continue) and the other 3 have their own tickets now.
