### ISSUE TITLE
Add explicit keyframe/thumb support to media resource model

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#56]
The base model for a resource of type=audio or video is just a recognized media file.  Extend the resource model for these to include a .jp2 file that can be used as a keyframe for a video before play, as background image for audio, for use in the resource index in embed.

**Comment by LynnMcRae** [comment]
I have added this to the contentMetadata model in consul -- https://consul.stanford.edu/display/chimera/DOR+content+types%2C+resource+types+and+interpretive+metadata

**Comment by hannahfrost** [comment]
looks good to me, @LynnMcRae
