### ISSUE TITLE
Do a full purl/embed end-to-end test for wacko chars in filename

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#61]
if there is a way to automate this, that would be great.  

We'd settle for manual testing proving that purl / embed / stacks / wowza works with filenames with weird chars.   Probably worth checking all of these:
- [ ] file (download)
- [ ] image (view)  (it's the identifier here, not the filename)
- [ ] media (stream)
- [ ] media (download)

@LynnMcRae created test data (such as fq961jm6386);

please pay particular attention, in all cases above, to things like
-  %20 in a filename (there's a real example, tho file is unpublished)
- extra . (periods) in a filename, besides the one for the extension (many real examples)
- spaces in filenames
- any other weird chars in real filenames (e.g. square brackets, question marks, parens, {} @#^ %|"` etc. )
- ensure that roundtrip of stacks-redirect --> wowza --> stacks token verification --> user works for weird chars in filenames

See https://github.com/sul-dlss/media/wiki/Examples-of-files-deposited-by-ETD-users,-special-characters-and-media-files 

Note that  latin1 foreign characters are not a requirement.

~~waiting on sul-dlss/digital_stacks_rails#49 to be deployed.~~

**Comment by ndushay** [comment]
fq961jm6386

**Comment by ndushay** [comment]
had trouble writing routing specs in digital_stacks_rails for  space  in filenames, and for ü.

**Comment by ndushay** [comment]
May need code tweaks to 
- [ ] sul-embed  (sul-dlss/sul-embed#578 )
- [ ] digital stacks (https://github.com/sul-dlss/digital_stacks_rails/issues/49)
- [ ] wowza (plugin code or configuration tweaks, esp for token validation hoo-ha?)

May need to document some forbidden chars, etc. for SDR deposit practices, etc.

**Comment by ndushay** [comment]
please pay particular attention to  things like

* %20  in a filename (there's a real example)
* extra . (periods)  in a filename, besides the one for the extension (many real examples)
* any other weird chars in real filenames  (e.g. square brackets, question marks, parens,   {} @#^ %|"`  etc. )

**Comment by ndushay** [comment]
code has been deployed to digital stacks and to wowza;  this is ready for testing.

**Comment by ndushay** [comment]
stacks file action for https://purl-test.stanford.edu/fq961jm6386   seems to fail on single quote  (or is it a backtick?  it's not encoded but the one in `cat's` is ...):

current sul-embed link looks like:

```
https://stacks-test.stanford.edu/media/fq961jm6386/Cat%20Noah,%20chattering%20@%20a%20fly%20%7Bbeing%20an%20observation%20of%20the%20phenomenon%20called%20'cat%20chattering'%7D%20...%20@?;=#$%^*.|-_+!,~%20Why%20do%20they%20do%20this?%20--%20[Is%20it%20a%20cat%27s%20way%20of%20talking%20to%20the%20animals?]%20(Seems%20a%20bit%20wacko!)++.mp4/stream.mpd
```

I think one implication is that sul-embed should (needs to?) encode, for media files (?) (seem to work for file request):

```
'   (not sure if this is backtick or single quote ...)
[
]
?
%
^
#
@
|
```

and possibly all but last dot for stream#download  request

**Comment by LynnMcRae** [comment]
Test objects:
https://purl-test.stanford.edu/ym777gf7400 -- for media
https://purl-test.stanford.edu/fg019pm1396 -- for image

**Comment by LynnMcRae** [comment]
Results documented in https://consul.stanford.edu/display/chimera/Character+set+constraints+for+SDR+file+names
