### ISSUE TITLE
embargo release still failing

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/media#68]
it appears that the embargo release query has been fixed, but something is wrong with the cron job:
https://github.com/sul-dlss/common-accessioning/issues/56#issuecomment-223356134

creating this proxy ticket to track track the follow on work, since the problem for which the initial issue was filed has been fixed.

**Comment by jmartin-sul** [comment]
the ticket for which this was a proxy has been closed, so closing the proxy ticket:  https://github.com/sul-dlss/common-accessioning/issues/56#event-684729989

feel free to reopen if this is in error.

**Comment by jmartin-sul** [comment]
reopening because it sounds like this still isn't working.  will follow up w/ lynn and whoever else he points me to.

**Comment by peetucket** [comment]
latest exception:

[lyberadmin@sul-robots1-test ~]$ cd /home/lyberadmin/common-accessioning/current/
[lyberadmin@sul-robots1-test current]$ BUNDLE_GEMFILE=/home/lyberadmin/common-accessioning/current/Gemfile ROBOT_ENVIRONMENT=test /usr/local/rvm/wrappers/default/ruby /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb
Loading config from /home/lyberadmin/common-accessioning/current/config/environments/test
DEPRECATION WARNING: Dor::Config -- solrizer configuration is deprecated. Please use solr instead. (called from <top (required)> at /home/lyberadmin/common-accessioning/current/config/environments/test.rb:3)
/home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:13: warning: already initialized constant ENABLE_SOLR_UPDATES
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/active-fedora-6.7.3/lib/active_fedora.rb:13: warning: previous definition of ENABLE_SOLR_UPDATES was here
D, [2016-06-07T14:53:16.639176 #1737] DEBUG -- : Loaded datastream list for druid:kn280cs8150 (67.3ms)
D, [2016-06-07T14:53:16.722530 #1737] DEBUG -- : Loaded datastream profile druid:kn280cs8150/RELS-EXT (80.8ms)
D, [2016-06-07T14:53:16.803216 #1737] DEBUG -- : Loaded datastream content druid:kn280cs8150/RELS-EXT (74.5ms)
D, [2016-06-07T14:53:16.885258 #1737] DEBUG -- : Loaded datastream profile druid:kn280cs8150/workflows (76.5ms)
D, [2016-06-07T14:53:21.979189 #1737] DEBUG -- : Loaded datastream list for druid:mt134rb1849 (81.3ms)
D, [2016-06-07T14:53:22.048149 #1737] DEBUG -- : Loaded datastream profile druid:mt134rb1849/RELS-EXT (67.3ms)
D, [2016-06-07T14:53:22.119108 #1737] DEBUG -- : Loaded datastream content druid:mt134rb1849/RELS-EXT (69.2ms)
D, [2016-06-07T14:53:22.180513 #1737] DEBUG -- : Loaded datastream profile druid:mt134rb1849/workflows (59.6ms)
D, [2016-06-07T14:53:22.983316 #1737] DEBUG -- : Loaded datastream list for druid:my974mh9308 (86.0ms)
D, [2016-06-07T14:53:23.089404 #1737] DEBUG -- : Loaded datastream profile druid:my974mh9308/RELS-EXT (103.3ms)
D, [2016-06-07T14:53:23.153832 #1737] DEBUG -- : Loaded datastream content druid:my974mh9308/RELS-EXT (63.4ms)
D, [2016-06-07T14:53:23.227182 #1737] DEBUG -- : Loaded datastream profile druid:my974mh9308/workflows (70.1ms)
D, [2016-06-07T14:53:25.788271 #1737] DEBUG -- : Loaded datastream list for druid:px885wv4511 (83.5ms)
D, [2016-06-07T14:53:25.874638 #1737] DEBUG -- : Loaded datastream profile druid:px885wv4511/RELS-EXT (82.7ms)
D, [2016-06-07T14:53:25.978890 #1737] DEBUG -- : Loaded datastream content druid:px885wv4511/RELS-EXT (102.4ms)
D, [2016-06-07T14:53:26.065019 #1737] DEBUG -- : Loaded datastream profile druid:px885wv4511/workflows (83.1ms)
/home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:561:in `rescue in workflow_resource_method': Failed to retrieve resource: put https://lyberservices-test.stanford.edu/workflow//dor/objects/druid:px885wv4511/workflows/disseminationWF/embargo-release (HTTP status 500) (Dor::WorkflowException)
from /home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:551:in`workflow_resource_method'
from /home/lyberadmin/common-accessioning/shared/bundle/ruby/2.2.0/gems/dor-workflow-service-2.0.1/lib/dor/services/workflow_service.rb:162:in `update_workflow_error_status'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:49:in`rescue in block in release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:37:in `block in release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in`each'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:36:in `release_items'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:57:in`release'
from /home/lyberadmin/common-accessioning/current/robots/accession/embargo_release.rb:67:in `<main>’

**Comment by jmartin-sul** [comment]
vague memories of having to set up the dor-workflow-services client properly.  this seems like a possible dor-services or dor-workflow-services misconfig.  it's been a couple months since i've looked at that stuff at all.

**Comment by LynnMcRae** [comment]
Would anyone be up for simply putting the latest fix into prod and seeing if it works?  It can't do any harm and it might get us past being stuck on an inadequate stage setup. I know I am suggesting a terrible thing, but we've done it once already trying to get this thing to work!

**Comment by jmartin-sul** [comment]
keeping this proxy ticket, updated title for accuracy, new common accessioning ticket:  sul-dlss/common-accessioning#60

**Comment by jmartin-sul** [comment]
also, i cleared size on this since it was a 3, and this is the second time this proxy ticket has been reopened/repurposed.  i could also put back an estimate that reflects the total estimate of the now three tickets that have been proxied by this.  but it seemed wrong to leave the original estimate in place considering the way this issue's scope has shifted.

**Comment by peetucket** [comment]
you can re-estimate...though leaving the original estimate is not necessary the wrong thing to do --- it lets us know we thought it was easier than it ended up being (which is also useful history) and therefore more correctly identifies the velocity

**Comment by jmartin-sul** [comment]
added the original estimate back.

so the original was a 3.  cron job thing feels like it'd have also been estimated at around a 3.  this new one feels to me like a 3 or a 5?

would you prefer just keeping the original 3, or doing some summation of the values for all three proxied tickets?

**Comment by ndushay** [comment]
New approach:  actually get it working in stage environment.

Task is to assess and document expected work necessary.   Hopefully this is max 3 hours (to assess).

**Comment by ndushay** [comment]
current ticket is sul-dlss/common-accessioning#60 ;  see info there.

**Comment by ndushay** [comment]
This is, effectively, the code to do an embargo_release:

```
embargo_druids.each do | druid |
 item=Dor::Item.find("druid:#{druid}")
 item.open_new_version
 item.release_embargo("application::accessionWF:embargo-release")
 item.close_version :description => "embargo released", :significance => :admin
 item.save
 puts "#{druid} embargo released"
end
```

 We are currently failing on `open_new_version` with `404: resource not found; MoabObject exception (couldn't run SDR current version call)`

Note that there may be failures with `release_embargo` or other steps after we get `open_new_version` to work.

---

We surmise the problem with `open_new_version` is a configuration issue.  

Theory (for failing SDR request): common_accesioning code is using old method of connecting to SDR directly rather than going through dor-services app.  We are suspicious of the settings for connecting to SDR.

Possible Solution?
- upgrade common_accessioning to latest dor-services gem  in a branch
- update deployed configuration to use new sdr proxy style
- deploy branch

estimate: a "waffle" 3 or maybe a 5 or maybe ...

then, test it, of course.

**Comment by ndushay** [comment]
embargo release processing documented here:  https://github.com/sul-dlss/argo/wiki/Embargo-Release-Processing

**Comment by LynnMcRae** [comment]
FYI incase it hasn't been conveyed yet ... you will be unable to open a new version in stage for any object copied over "accessioned" but never ingested.  It is a legitimate error when SDR says you can't open a v2 because there is no v1 in pres core. Unfortunately, this is the state of the vast majority of dor-test objects.  If you don't have some street legal test embargo objects yet, I'll work with Ben to make a couple.

**Comment by ndushay** [comment]
yes, please, make us some street legal embargo-able objects!   We think we got one thru: kn280cs8150   but we didn't know how to reset it to be embargoed again.

**Comment by LynnMcRae** [comment]
druid:kn280cs8150 and druid:px885wv4511 look like usable examples in stage. I set them both back to being embargoed and can reset them quickly as needed.

**Comment by LynnMcRae** [comment]
An embargoed datastream looks like this

```
<embargoMetadata>
  <status>embargoed</status>
  <releaseDate>2016-06-13T08:00:00Z</releaseDate>
  <twentyPctVisibilityStatus/>
  <twentyPctVisibilityReleaseDate/>
  <releaseAccess>
    <access type="discover">
      <machine>
        <world/>
      </machine>
    </access>
    <access type="read">
      <machine>
        <world/>
      </machine>
    </access>
  </releaseAccess>
</embargoMetadata>
```

Embargo release replaces the object level rights in rightsMetadata with the contents of <releaseAccess> and then sets the status to "release". 

rightsMetadata for an item under embargo looks like this: 

```
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <embargoReleaseDate>2016-06-13T08:00:00Z</embargoReleaseDate>
      <none/>
    </machine>
  </access>
  ...etc...
```

The two expressions of release date should match of course, and be in the past to be caught by the embargo release job's query.

**Comment by ndushay** [comment]
We believe we have solved this problem.  See sul-dlss/common-accessioning/issues/60.

We kicked off the embargo release from the command line (just as the cron job would) and it is running now, error free!

We will be deploying common_accessioning code with the dor-services gem upgrade to 5.8.0 (was 5.7.0) at your earliest convenience.

**Comment by ndushay** [comment]
closing in favor of #80
