### ISSUE TITLE
sul-streaming: media content from old server to new server

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#72]
- ~~[ ] copy HTML from old server to new VM~~  this is now a separate issue, #78
- [x] copy flash video and MP3 files from old server to Wowza-prod (into `/data/sul-streaming` directory

**Comment by ndushay** [comment]
scp?  temporary mount of existing content volume onto wowza box.

**Comment by ndushay** [comment]
media content is at `/usr/local/wow/content`

username media for sul-streaming;  could ssh from wowza-stage but not from my laptop

**Comment by ndushay** [comment]
Rob suggests  rsync or scp

**Comment by ndushay** [comment]
sul-streaming  `/usr/local/wow/content`:  uses 498G

sul-wowza-prod  `/data` : has 700G avail

**Comment by ndushay** [comment]
This means we explicitly know we do NOT need:

```
kant
tanner
zimbardo
```

but not yet sure about other content in dirs starting other than sc, v0, or feigenbaum

**Comment by ndushay** [comment]
I copied all the media from sul-streaming  in `/usr/local/wow/content/` EXCEPT:

```
kant
linked_data_workshop  # empty dir
merry_melodies_falling_hare.flv
o-canada-1914.mp3
parker_tutorials_test
tanner
test
zimbardo
```

**Comment by ndushay** [comment]
Just in case, i put `kant`, `tanner` and `zimbardo` on sul-wowza in a subdir: `/data/sul-streaming/prob-dont-need`

**Comment by ndushay** [comment]
@hannahfrost  does this sound okay to you?

I copied all the media from sul-streaming  in `/usr/local/wow/content/` EXCEPT:

```
linked_data_workshop  # empty dir
merry_melodies_falling_hare.flv
o-canada-1914.mp3
parker_tutorials_test
test
```

Just in case, i put `kant`, `tanner` and `zimbardo` on sul-wowza in a subdir: `/data/sul-streaming/prob-dont-need`

**Comment by hannahfrost** [comment]
@ndushay Yes, that sounds right to me. Thank you!
