### ISSUE TITLE
sul-streaming:  build new wowza application for  Flash/MP3 files

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#73]
app name:   sul-streaming
content will live in:    /data/sul-streaming      (that is, the mounted data directory, with a sub-directory of sul-streaming, and preserving the old directory structure under that)

we will create a wowza app on -stage   first just to ensure we can set up the configuration properly, then we will set the analogous wowza app up on wowza-prod.

**Comment by ndushay** [comment]
test video with wowza admin gui:

media file name:  

adobe RTMP:
- v0058/pw607mn4286_web.flv  
- v0058/vn286qc7384_web.flv

other content on -stage (some of it) (you have to specify mp3):
- sc0359/ct119fk4153_a_sl.mp3
- sc0359/ct119fk4153_b_sl.mp3
- sc0359/nt777wt9736_1_a_sl.mp3
- sc0359/nt777wt9736_2_b_sl.mp3
- sc0359/vm724dd0090_1_a_sl.mp3
- sc0359/vm724dd0090_3_b_sl.mp3
- sc0359/vq083my4984_a_sl.mp3
- sc0359/yj795cr5189_b_sl.mp3

**Comment by ndushay** [comment]
I believe I have correctly configured the sul-streaming wowza "application" on  wowza-stage and wowza-prod.   In both cases, the content is expected in the `/data/sul-streaming` folder.
