### ISSUE TITLE
sul-streaming: create alias rules

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#75]
- [ ] turn sul-streaming into an alias for streaming-legacy, but keep sul-streaming box

This will allow folks pointing to the HTML from sul-streaming to be using new, improved HTML on streaming legacy that plays video from new wowza box.

See https://consul.stanford.edu/display/GAL/sul-streaming+migration and SAR-3189, SAR-3157

**Comment by ndushay** [comment]
Waiting for wowza-prod box to get apache server and htm, jsl content from sul-streaming.

**Comment by ndushay** [comment]
blocked only in that it needs sign off that our migration is ok:
- collections.stanford.edu  bucky and mjf
- anything else pointing to sul-streaming

**Comment by ndushay** [comment]
@hannahfrost   I have added suggestions to https://docs.google.com/document/d/1_gHNpzfohbLlE2SjdgxS7O0x-aeEWBOspU_BJVGe_Go/edit?ts=577eaa39#

it was not quite correct.

**Comment by ndushay** [comment]
I'm calling this done.  Still have a few tendrils to "productionize" streaming-legacy box, but those are in progress and recorded on #94:
- [ ]  nagios checks for streaming-legacy (SAR-3210)
- [ ]  remove nagios checks for sul-streaming-old (SAR-3210)
- [ ]  log retention for streaming-legacy (SAR-3211)
