### ISSUE TITLE
sul-streaming: update HTML player links to new media locations

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#76]
when the html/js is copied to the new VM, the links to the streaming content will need to be changed from the old sul-streaming server to the new wowza-prod sul-streaming (wowza) application URLs.

**Comment by ndushay** [comment]
Per #78, the html/js etc  has been moved to new streaming-legacy VM in `/opt/app/wowza`

Per #75 and #73, the media content is now available on sul-wowza-prod  in the  sul-streaming  application.

So all links in html / js  to the actual media content should now be changed.

**Comment by ndushay** [comment]
This returns html   

https://streaming-legacy.stanford.edu/collections/hershman/war/antoni_2006.html   

So we have web server up and running and ready for getting the updated links to media living on new wowza.

**Comment by ndushay** [comment]
example of working new url for flv

`rtmp://sul-mediaserver.stanford.edu:1935/sul-streaming/_definst_/v0058/vn286qc7384_web.flv`

where v0058  is the "collection" directory

**Comment by ndushay** [comment]
Just filed SAR-3185  to open prod wowza port 1935  so video is actually viewable from that box ...

**Comment by ndushay** [comment]
wowza-prod  sul-streaming videos now actually play!

**Comment by tingulfsen** [comment]
I'm closing this ticket having completed the migration of content from the old sul-streaming to the new streaming-legacy server. I've done a little bit of testing manually without finding any problems. If anything crops up, we could just open a new issue.

Note that there is a separate ticket (#86) for migrating collections.stanford.edu.
