### ISSUE TITLE
Special characters causes display problem with image embed

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/media#79]
This is a proxy ticket for https://github.com/sul-dlss/sul-embed/issues/595 where embed has display problems with a test object originally created as part of the media effort to test character set limitations with odd filenames through Stacks -- https://purl-test.stanford.edu/fg019pm1396

**Comment by jkeck** [comment]
SUL-Embed is part of the Media waffle board.  Why has this additional proxy ticket been created?

We typically have done this for projects that are not in our waffle board so we don't have to pull in all of their issues into our backlog, but these seems like unnecessary duplication and overhead in ticketing.

**Comment by LynnMcRae** [comment]
d'oh, my bad ... was thinking more of "image" not being in scope for media than about the project itself, but basically  just forgot it was already there. I assume we will ignore the underlying issue for now as it's not relevant to this sprint.
