### ISSUE TITLE
deploy to production for vetting non-media changes

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#85]
deploy sul-embed with media turned off
deploy digital stacks 

get a production shakedown while media team still focused on media

**Comment by ndushay** [comment]
I don't remember why I put the blocked label on this.  Are we waiting for digital_stacks fixes and sul-embed fixes first?

**Comment by jkeck** [comment]
Yeah, I believe we want to get sul-dlss/sul-embed#598 merged in first.  We should also get some testing done on `stacks-test`/`purl-test`.

We should chat about the testing plan at our check-in tomorrow (although perhaps critical people will not be there).

**Comment by jkeck** [comment]
Closing in exchange for larger UAT for full stack.
