### ISSUE TITLE
evaluate streaming file encoding specifications

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/media#9]
SMPL staff currently create derivatives that should be streamable by Wowza. We'll start by using those. Yet eventually we will want to evaluate the encodings with a player or players and under different network/delivery scenarios.

Encoding specs currently used by Avalon (with Adobe Streaming Server, not Wowza): https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Derivatives

**Comment by peetucket** [comment]
Questions to be ansewered:
- [ ] what formats do we need to support (audio and video)
- [ ] how many and what derivatives do we need to generate (depends on if we are we supporting variable rate streaming)
- [ ] how many download variants do we need to generate
