### ISSUE TITLE
Analysis of location based restricted images

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/media#93]
- [x] IIIF manifest changes
- [ ] Designs
- [ ] SUL Embed Viewer Changes

**Comment by LynnMcRae** [comment]
Cover story ticket - https://github.com/sul-dlss/sul-embed/issues/597

**Comment by peetucket** [comment]
What work would need to be done to support location-restricted access for image content?

**Comment by LynnMcRae** [comment]
Good test object -- https://sul-purl-test.stanford.edu/pn861pp0444 -- the second pictures is location protected, the third is location protected with no-download.

**Comment by LynnMcRae** [comment]
Note, the analysis for IIIF Manifest changes has been moved to https://consul.stanford.edu/display/digistacks/Adding+location+restrictions+to+the+image+IIIF+Manifest

**Comment by hannahfrost** [comment]
@LynnMcRae I will take over this ticket and ask @jvine to advise on any design changes to support this work.

**Comment by hannahfrost** [comment]
Based on my last discussion with @LynnMcRae, the next step is to discuss with Jessie and Peter.

**Comment by hannahfrost** [comment]
This work has been addressed in the meantime.
