### ISSUE TITLE
Spot-check content that has been migrated to sul-streaming

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/media#95]
1. MJF (test all) and Bucky material (spot check) - served by collections.stanford.edu

**Comment by ndushay** [comment]
Also want comparison of  sul-streaming  html    with streaming-legacy html:    it should be exactly comparable and videos and audio should play on streaming-legacy.

Folders of content on streaming-legacy box.    Login and go to `collections` directory and have at it.

**Comment by peetucket** [comment]
MJF and Bucky spot checks look good (all of MJF checked)

**Comment by peetucket** [comment]
spot-checked about 20 files scattered throughout streaming-legacy folders and all worked (found both video and audio)
