### ISSUE TITLE
Wowza: upgrade wowza-prod to latest wowza version

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/media#98]
(devops-y):

from @tingulfsen:

"be aware that /usr/local now contains another Wowza directory for the latest version (Erin set that one up)."

**Comment by ndushay** [comment]
done for -dev and -stage;   -prod is still at 4.1.2

**Comment by peetucket** [comment]
waiting for Tommy to return to confirm details

**Comment by ndushay** [comment]
@tingulfsen sent an email to @eefahy about upgrading wowza on our prod box.  Perhaps he could paste it in here for the record?

**Comment by ndushay** [comment]
@tingulfsen :  fyi:  just spoke to erin and she says to schedule a meeting with her (you and her) to get the puppet changes, etc. you need to upgrade wowza to 4.5.0 on the prod box.

**Comment by ndushay** [comment]
tied to sul-dlss/dlss-wowza#35

**Comment by ndushay** [comment]
done today thanks to @eefahy !
