### ISSUE TITLE
location etc rights facet:  deploy argo 3.4.0 to prod, reindex all objects

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/media#99]
as per the last comment on sul-dlss/dor-rights-auth#17, the deployment and indexing should be all that remain to get the new rights facet into production.  we'll deploy and start the indexing on monday, since there's heavy accessioning happening for the rest of this week, and we don't want to risk overloading fedora.

opening this ticket for the deployment stuff, since the old ticket was about implementation, which should be done at this point (and this last deployment part is more appropriately tracked in the media project or the argo project, since dor-rights-auth itself doesn't get deployed anywhere).

**Comment by jmartin-sul** [comment]
indexing was proceeding without error, but very slowly when it started (on track to take around 68 days to do all 1.2+ million objects in fedora).  a bit of profiling using argo's [RubyProf tools](https://github.com/sul-dlss/argo/blob/master/PROFILING.md) indicated that the new relic profiling agent was taking up what seemed like an inordinate amount of the runtime, more than anything else, including the I/O waits associated with requests to fedora and solr.  disabling the new relic profiling agent appeared to speed things up greatly, and now the indexing is on track to complete in around 10 days total at the current rate.  @blalbrit says this is acceptable.  it's also in line with what we saw from the full reindex for the argo 3 release in march.  that took just under 4 days, but there were only around 900k objects to index, and there were more workers for the first half of that indexing run (16 each on prod-a and prod-b, which we reduced to 12 workers per machine for stability reasons).  my guess is that new relic was disabled for that earlier full indexing run, though i could be wrong about that.  it is also possible that the new relic ruby agent has changed between minor versions, and that it now introduces more overhead.  whatever the underlying issue, disabling it seems to speed things up.

**Comment by jkeck** [comment]
Just out of curiosity, was the New Relic profiling being reported anywhere?

**Comment by jmartin-sul** [comment]
i believe it was being collected in the DLSS new relic account, but i haven't looked in a while.  @eefahy might know?  i believe she set the license key up.

**Comment by jmartin-sul** [comment]
the indexing is pretty much all done.

one straggler batch of objects remains in the indexing job queue.  i will look at its list of druids and try to run them manually (assuming some subset of the druids is failing, and keeping the batch from completing successfully).

**Comment by jmartin-sul** [comment]
on monday, i deleted the job for the aforementioned straggler, and re-ran the 10 objects in it by hand (by hitting dor-indexing-app using the browser).  9/10 ran successfully.  this one hung without ever returning or erroring:  https://argo.stanford.edu/catalog/druid:tw738dt3374

the logs showed 163 objects failed to index successfully over the course of the run.  attaching a list of druids for all objects that failed to index, a couple sub-lists broken out by particular error types, and a list with the actual log entries for the errors, which contain stack traces that point to the causes of the indexing failures.

[druids_that_failed_to_index-all.txt](https://github.com/sul-dlss/media/files/400329/druids_that_failed_to_index-all.txt)
[druids_that_failed_to_index-fedora_conn_err-all.txt](https://github.com/sul-dlss/media/files/400326/druids_that_failed_to_index-fedora_conn_err-all.txt)
[druids_that_failed_to_index-sw_language_facet-all.txt](https://github.com/sul-dlss/media/files/400328/druids_that_failed_to_index-sw_language_facet-all.txt)
[indexing-errors-all.txt](https://github.com/sul-dlss/media/files/400327/indexing-errors-all.txt)

**Comment by blalbrit** [comment]
Checking in on some of the above, the index-fedora_conn_err errors were just time-out errors and have been manually reindexed.

**Comment by blalbrit** [comment]
The language facet failures seem to be failing on the isocode "bla" (the Siksika language). I wonder if that particularly language code is supported in our environment? These all appear to be from a single collection. Would @ndushay know about language code support and potential errors?

**Comment by blalbrit** [comment]
Lynn and I have both looked at tw738dt3374 - there is something weird and recursive going on there and we'll need to look further.

**Comment by LynnMcRae** [comment]
re tw738dt3374  -- d'oh!  we knew this one... stack too deep error is because the collection it belongs to is a member of itself and something in the indexing chases its own tail when  dereferencing the collection druid for the item.  Collection object druid:wn316fx5031 fixed, tw738dt3374 now reindexes.

**Comment by blalbrit** [comment]
@peetucket - I'm reopening until we can determine the language facet indexing error source.

**Comment by LynnMcRae** [comment]
For first object in the list https://argo.stanford.edu/catalog/druid:bd752zt0985
The language statement looked like this:

```
<languageTerm valueURI="http://id.loc.gov/vocabulary/iso639-2/eng" type="code">eng</languageTerm>
```

I added - authority="iso639-2b"  to make it 

```
<languageTerm authority="iso639-2b" valueURI="http://id.loc.gov/vocabulary/iso639-2/eng" type="code">eng</languageTerm>
```

and it indexes successfully. Can't tell if the dependency is on the authority attribute regardless of value, or specifically iso639; I suspect the former since it likely expects codes to be governed by some authority/vocabulary and an external source URI doesn't cover that.

**Comment by LynnMcRae** [comment]
re: recursion error, the ticket for this was https://jirasul.stanford.edu/jira/browse/STNFRDSYNC-129 but has been marked closed. I thought it might be because we made a github ticket but I can't find one.  I'll make one unless someone knows of one I'm not seeing.

**Comment by ndushay** [comment]
so is this ticket done now?  should it be closed?

**Comment by blalbrit** [comment]
Yep. Sorry - should have followed that up after Lynn found the language issue.
